import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { classNames } from "@/shared/lib/helpers/classNames";
import Script from "next/script";
import { RootProvider } from "./_providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "h-screen flex flex-col relative"
        )}
      >
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive"></Script>
        <RootProvider>
        <header></header>
        <main className="flex-1">{children}</main>
        <footer></footer>
        </RootProvider>
      </body>
    </html>
  );
}
